name: Java CI with Maven

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

permissions:
  contents: read
  packages: write

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4.7.0
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: maven

      # Fix for Dependency Graph Submission
      - name: Update dependency graph
        uses: advanced-security/maven-dependency-submission-action@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Cache Maven packages
        uses: actions/cache@v3
        with:
          path: ~/.m2
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-
  
      - name: Install dependencies
        run: mvn install -DskipTests

      - name: Run tests and generate Allure results
        run: mvn clean test

      - name: Generate Allure Report
        run: mvn allure:report

      - name: Upload Allure Report as Artifact (Fix for v4)
        uses: actions/upload-artifact@v4
        with:
          name: allure-report
          path: target/site/allure-maven-plugin/
          compression-level: 0  # Optional: Avoids excessive compression

      # Email Notification Step
      - name: Send Email Notification with Allure Report
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.gmail.com
          server_port: 587
          username: ${{ secrets.EMAIL_USERNAME }}
          password: ${{ secrets.EMAIL_PASSWORD }}
          subject: "Allure Test Report - Build ${{ github.run_number }}"
          body: "Hello,\n\nAttached is the latest Allure report for the test run.\n\nBest Regards,\nGitHub Actions"
          to: mahmoudkhallaf277@gmail.com
          from: GitHub Actions <${{ secrets.EMAIL_USERNAME }}>
          attachments: target/site/allure-maven-plugin/index.html
